### PR TITLE
The Sponsor role or Initial Authorizer need to have the ability to su…

### PR DESCRIPTION
**Pull request by shahbazkhan1999**

### CODE REVIEW

**Review by spetros-do — APPROVED** [review]
The logic checks out ok. It allows additional role check as intended. 
Only suggestion I have is on the Error Msg to include a mention of the 'Initial Authorizer' to avoid confusion and accurately reflect the update.

**Comment by spetros-do** [comment]
M

**Comment by spetros-do** [comment]
Closed it by accident. I presume our internal process is that "pull requester" will merge to the branch once getting approval.

**Comment by shahbazkhan1999** [comment]
Hi @spetros-do I updated the error message as asked in the PR review, please check and approve it, if it's good.

**Pull request merged**
